[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/"
]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default.metadata]
bytecode_hash = "ipfs"
use_literal_content = false
cbor_metadata = true

[profile.default.output_selection]
"*" = ["evm.bytecode", "evm.deployedBytecode", "devdoc", "userdoc", "metadata", "abi"]

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
monad = "https://testnet-rpc.monad.xyz"

[etherscan]
avalanche = { key = "verifyContract", url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
monad = { key = "", url = "" }

# Monad Testnet Configuration
[profile.chains.10143]
name = "monad"
chain_id = 10143
eth-rpc-url = "https://testnet-rpc.monad.xyz"
verifier = "sourcify"
verifier_url = "https://sourcify-api-monad.blockvision.org"

# Avalanche C-Chain Configuration
[profile.chains.43114]
name = "avalanche"
chain_id = 43114
eth-rpc-url = "https://api.avax.network/ext/bc/C/rpc"
verifier = "etherscan"
verifier_url = "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan"

[profile.test]
src = "test"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[profile.release]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/"
]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"
